### ISSUE TITLE
ゲーム開始時（タイトルのボタンを押したとき）にアプリが落ちる

### ISSUE THREAD

**Issue by dko5ki23t** [dko5ki23t/box_pusher#6]
エラーまんまコピー：
Launching lib\main.dart on Pixel 7 Pro in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:54088/K3sqMq1YJeU=/ws
I/DynamiteModule(21167): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:243799204
I/DynamiteModule(21167): Selected remote version of com.google.android.gms.ads.dynamite, version >= 243799204
D/DynamitePackage(21167): Instantiated singleton DynamitePackage.
D/DynamitePackage(21167): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
I/Ads     (21167): Updating ad debug logging enablement.
W/Sensors (21167): Cannot get virtualdevice_native service
W/ziparchive(21167): Unable to open '/data/app/~~JiLom7AHHYkvO5Jc32WZyA==/com.google.android.trichromelibrary_672308633-ArQgg4QLdU2VMUaCNc-1YQ==/base.dm': No such file or directory
W/ziparchive(21167): Unable to open '/data/app/~~JiLom7AHHYkvO5Jc32WZyA==/com.google.android.trichromelibrary_672308633-ArQgg4QLdU2VMUaCNc-1YQ==/base.dm': No such file or directory
W/mple.box_pusher(21167): Entry not found
D/nativeloader(21167): Configuring clns-11 for other apk /data/app/~~JiLom7AHHYkvO5Jc32WZyA==/com.google.android.trichromelibrary_672308633-ArQgg4QLdU2VMUaCNc-1YQ==/base.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~8tS8oZ23tZGrGhCgsBX9Jw==/com.google.android.webview-5CPAc6pCHbHStPho91c9EA==/lib/arm64:/data/app/~~8tS8oZ23tZGrGhCgsBX9Jw==/com.google.android.webview-5CPAc6pCHbHStPho91c9EA==/base.apk!/lib/arm64-v8a:/data/app/~~JiLom7AHHYkvO5Jc32WZyA==/com.google.android.trichromelibrary_672308633-ArQgg4QLdU2VMUaCNc-1YQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
D/nativeloader(21167): Extending system_exposed_libraries: libedgetpu_dba.google.so
W/mple.box_pusher(21167): Loading /data/app/~~8tS8oZ23tZGrGhCgsBX9Jw==/com.google.android.webview-5CPAc6pCHbHStPho91c9EA==/oat/arm64/base.odex non-executable as it requires an image which we failed to load
D/nativeloader(21167): Configuring clns-12 for other apk /data/app/~~8tS8oZ23tZGrGhCgsBX9Jw==/com.google.android.webview-5CPAc6pCHbHStPho91c9EA==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~8tS8oZ23tZGrGhCgsBX9Jw==/com.google.android.webview-5CPAc6pCHbHStPho91c9EA==/lib/arm64:/data/app/~~8tS8oZ23tZGrGhCgsBX9Jw==/com.google.android.webview-5CPAc6pCHbHStPho91c9EA==/base.apk!/lib/arm64-v8a:/data/app/~~JiLom7AHHYkvO5Jc32WZyA==/com.google.android.trichromelibrary_672308633-ArQgg4QLdU2VMUaCNc-1YQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
I/WebViewFactory(21167): Loading com.google.android.webview version 130.0.6723.86 (code 672308633)
I/cr_WVCFactoryProvider(21167): version=130.0.6723.86 (672308633) minSdkVersion=29 isBundle=true multiprocess=true packageId=2
D/nativeloader(21167): Load /data/app/~~JiLom7AHHYkvO5Jc32WZyA==/com.google.android.trichromelibrary_672308633-ArQgg4QLdU2VMUaCNc-1YQ==/base.apk!/lib/arm64-v8a/libmonochrome_64.so using ns clns-12 from class loader (caller=/data/app/~~8tS8oZ23tZGrGhCgsBX9Jw==/com.google.android.webview-5CPAc6pCHbHStPho91c9EA==/base.apk): ok
D/nativeloader(21167): Load /system/lib64/libwebviewchromium_plat_support.so using ns clns-12 from class loader (caller=/data/app/~~8tS8oZ23tZGrGhCgsBX9Jw==/com.google.android.webview-5CPAc6pCHbHStPho91c9EA==/base.apk): ok
I/chromium(21167): [1113/154716.145920:INFO:variations_seed_loader.cc(68)] Failed to open file for reading.: No such file or directory (2)
I/cr_LibraryLoader(21167): Successfully loaded native library
I/cr_CachingUmaRecorder(21167): Flushed 6 samples from 6 histograms, 0 samples were dropped.
I/cr_CombinedPProvider(21167): #registerProvider() provider:WV.z8@db81130 isPolicyCacheEnabled:false policyProvidersSize:0
I/cr_PolicyProvider(21167): #setManagerAndSource() 0
I/cr_CombinedPProvider(21167): #linkNativeInternal() 1
I/cr_AppResProvider(21167): #getApplicationRestrictionsFromUserManager() Bundle[EMPTY_PARCEL]
I/cr_PolicyProvider(21167): #notifySettingsAvailable() 0
I/cr_CombinedPProvider(21167): #onSettingsAvailable() 0
I/cr_CombinedPProvider(21167): #flushPolicies()
D/CompatibilityChangeReporter(21167): Compat change id reported: 214741472; UID 10417; state: ENABLED
D/CompatibilityChangeReporter(21167): Compat change id reported: 171228096; UID 10417; state: ENABLED
W/Ads     (21167): Update ad debug logging enablement as false
W/cr_media(21167): BLUETOOTH_CONNECT permission is missing.
W/cr_media(21167): getBluetoothAdapter() requires BLUETOOTH permission
W/cr_media(21167): registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
W/mple.box_pusher(21167): Accessing hidden field Landroid/content/pm/ApplicationInfo;->primaryCpuAbi:Ljava/lang/String; (unsupported, reflection, allowed)
W/chromium(21167): [WARNING:viz_main_impl.cc(85)] VizNullHypothesis is disabled (not a warning)
D/CompatibilityChangeReporter(21167): Compat change id reported: 263076149; UID 10417; state: DISABLED
I/Ads     (21167): JS: The jsLoaded GMSG has been sent (https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html:796)
I/chromium(21167): [INFO:CONSOLE(796)] "The jsLoaded GMSG has been sent", source: https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html (796)
D/CompatibilityChangeReporter(21167): Compat change id reported: 247079863; UID 10417; state: DISABLED
D/MediaCodecList(21167): codecHandlesFormat: no format, so no extra checks
D/CCodec  (21167): allocate(c2.android.mp3.decoder)
I/Codec2Client(21167): Available Codec2 services: "default" "default1" "default2" "software"
I/CCodec  (21167): setting up 'default' as default (vendor) store
I/CCodec  (21167): Created component [c2.android.mp3.decoder]
D/CCodecConfig(21167): read media type: audio/mpeg
D/ReflectedParamUpdater(21167): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(21167): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(21167): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(21167): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(21167): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(21167): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(21167): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(21167): query failed after returning 8 values (BAD_INDEX)
D/CCodecConfig(21167): c2 config diff is Dict {
D/CCodecConfig(21167):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(21167):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(21167):   c2::u32 input.delay.value = 0
D/CCodecConfig(21167):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig(21167):   c2::u32 output.large-frame.max-size = 0
D/CCodecConfig(21167):   c2::u32 output.large-frame.threshold-size = 0
D/CCodecConfig(21167):   string output.media-type.value = "audio/raw"
D/CCodecConfig(21167):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(21167):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(21167): }
D/CCodec  (21167): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(21167): no c2 equivalents for durationUs
D/CCodecConfig(21167): no c2 equivalents for track-id
D/CCodecConfig(21167): no c2 equivalents for encoder-delay
D/CCodecConfig(21167): no c2 equivalents for encoder-padding
D/CCodecConfig(21167): no c2 equivalents for flags
D/CCodecConfig(21167): c2 config diff is   c2::u32 coded.bitrate.value = 192000
W/Codec2Client(21167): query -- param skipped: index = 1107298332.
D/CCodec  (21167): encoding statistics level = 0
D/CCodec  (21167): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (21167):   int32_t bitrate = 192000
D/CCodec  (21167):   int32_t channel-count = 2
D/CCodec  (21167):   int32_t max-input-size = 8192
D/CCodec  (21167):   string mime = "audio/mpeg"
D/CCodec  (21167):   int32_t sample-rate = 44100
D/CCodec  (21167): }
D/CCodec  (21167): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  (21167):   int32_t buffer-batch-max-output-size = 0
D/CCodec  (21167):   int32_t buffer-batch-threshold-output-size = 0
D/CCodec  (21167):   int32_t channel-count = 2
D/CCodec  (21167):   string mime = "audio/raw"
D/CCodec  (21167):   int32_t sample-rate = 44100
D/CCodec  (21167):   int32_t encoder-delay = 576
D/CCodec  (21167):   int32_t encoder-padding = 952
D/CCodec  (21167):   int32_t android._config-pcm-encoding = 2
D/CCodec  (21167): }
I/CCodecConfig(21167): query failed after returning 8 values (BAD_INDEX)
W/Codec2Client(21167): query -- param skipped: index = 1342179345.
W/Codec2Client(21167): query -- param skipped: index = 2415921170.
D/C2Store (21167): debug.c2.use_dmabufheaps set, forcing DMABUF Heaps
D/C2Store (21167): Using DMABUF Heaps
D/CCodecBufferChannel(21167): [c2.android.mp3.decoder#485] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
I/CCodecBufferChannel(21167): [c2.android.mp3.decoder#485] Created output block pool with allocatorID 16 => poolID 3361 - OK
D/CCodecBufferChannel(21167): [c2.android.mp3.decoder#485] Configured output block pool ids 3361 => OK
I/DMABUFHEAPS(21167): Using DMA-BUF heap named: system
D/CCodecBufferChannel(21167): [c2.android.mp3.decoder#485] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(21167): [c2.android.mp3.decoder#485] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder(21167): onLastStrongRef automatically unlinking death recipients
V/MediaPlayer(21167): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(21167): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/AudioManager(21167): dispatching onAudioFocusChange(-1) to android.media.AudioManager@f1c384bxyz.luan.audioplayers.player.FocusManager$$ExternalSyntheticLambda0@d2d0228
V/MediaPlayer(21167): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(21167): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/AndroidRuntime(21167): Shutting down VM
E/AndroidRuntime(21167): FATAL EXCEPTION: main
E/AndroidRuntime(21167): Process: com.example.box_pusher, PID: 21167
E/AndroidRuntime(21167): java.lang.IllegalStateException
E/AndroidRuntime(21167): 	at android.media.MediaPlayer.getPlaybackParams(Native Method)
E/AndroidRuntime(21167): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.setRate(MediaPlayerPlayer.kt:45)
E/AndroidRuntime(21167): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.start(MediaPlayerPlayer.kt:64)
E/AndroidRuntime(21167): 	at xyz.luan.audioplayers.player.WrappedPlayer.onPrepared(WrappedPlayer.kt:279)
E/AndroidRuntime(21167): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.createMediaPlayer$lambda-5$lambda-0(MediaPlayerPlayer.kt:16)
E/AndroidRuntime(21167): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.$r8$lambda$-4npXJX7g82ISchzgofDoB2nPy8(Unknown Source:0)
E/AndroidRuntime(21167): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer$$ExternalSyntheticLambda0.onPrepared(Unknown Source:2)
E/AndroidRuntime(21167): 	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3516)
E/AndroidRuntime(21167): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(21167): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime(21167): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime(21167): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
E/AndroidRuntime(21167): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21167): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AndroidRuntime(21167): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
D/BufferPoolAccessor2.0(21167): bufferpool2 0xb400007724223c28 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/80 (fetch/transfer)
D/BufferPoolAccessor2.0(21167): evictor expired: 1, evicted: 1
I/mple.box_pusher(21167): Thread[2,tid=21168,WaitingInMainSignalCatcherLoop,Thread*=0xb4000076a416ef50,peer=0x141b0020,"Signal Catcher"]: reacting to signal 3
I/mple.box_pusher(21167):
I/mple.box_pusher(21167): Wrote stack traces to tombstoned
Lost connection to device.

Exited.

**Comment by dko5ki23t** [comment]
いつのまにやら起きなくなってる
